const CATEGORIES = [
  { key: "assistant", label: "对话助手", icon: "messages-square", color: "#16a34a" },
  { key: "code", label: "编程开发", icon: "code-2", color: "#2563eb" },
  { key: "image", label: "图像设计", icon: "image", color: "#ea580c" },
  { key: "video", label: "视频音频", icon: "clapperboard", color: "#db2777" },
  { key: "office", label: "效率办公", icon: "briefcase", color: "#0d9488" },
  { key: "search", label: "搜索研究", icon: "search", color: "#4f46e5" },
  { key: "life", label: "生活娱乐", icon: "smile", color: "#ca8a04" },
  { key: "data", label: "数据分析", icon: "chart-column-big", color: "#0891b2" },
];

const TOOLS = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    domain: "chatgpt.com",
    url: "https://chatgpt.com",
    desc: "OpenAI 推出的通用对话助手，支持多模态、联网搜索与自定义 GPT。",
    category: "assistant",
    tags: ["通用对话", "多模态", "智能体"],
    rating: 4.9,
    favs: 28640,
    pricing: "免费额度",
    platforms: ["Web", "iOS", "Android", "桌面"],
    featured: true,
    added: "2022-11",
  },
  {
    id: "claude",
    name: "Claude",
    domain: "claude.ai",
    url: "https://claude.ai",
    desc: "Anthropic 出品，长文本理解与写作能力出色，支持 Projects 和 Artifacts。",
    category: "assistant",
    tags: ["长文本", "写作", "编程"],
    rating: 4.8,
    favs: 24310,
    pricing: "免费额度",
    platforms: ["Web", "iOS", "Android", "桌面"],
    featured: true,
    added: "2023-03",
  },
  {
    id: "gemini",
    name: "Gemini",
    domain: "gemini.google.com",
    url: "https://gemini.google.com",
    desc: "Google 多模态 AI 助手，深度整合搜索、Gmail 与 Google 生态。",
    category: "assistant",
    tags: ["多模态", "Google 生态", "通用"],
    rating: 4.7,
    favs: 19560,
    pricing: "免费额度",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2023-12",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    domain: "chat.deepseek.com",
    url: "https://chat.deepseek.com",
    desc: "深度求索开源大模型对话助手，推理能力强，支持文件与联网。",
    category: "assistant",
    tags: ["开源", "推理", "中文"],
    rating: 4.8,
    favs: 22140,
    pricing: "免费",
    platforms: ["Web", "iOS", "Android"],
    featured: true,
    added: "2024-01",
  },
  {
    id: "kimi",
    name: "Kimi",
    domain: "kimi.moonshot.cn",
    url: "https://kimi.moonshot.cn",
    desc: "月之暗面出品，超长上下文阅读与资料整理能力强。",
    category: "assistant",
    tags: ["长上下文", "文档阅读", "中文"],
    rating: 4.7,
    favs: 17430,
    pricing: "免费",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2023-10",
  },
  {
    id: "doubao",
    name: "豆包",
    domain: "doubao.com",
    url: "https://www.doubao.com",
    desc: "字节跳动全能 AI 助手，集成对话、写作、图像与智能体能力。",
    category: "assistant",
    tags: ["全能助手", "中文", "智能体"],
    rating: 4.6,
    favs: 16820,
    pricing: "免费",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2023-08",
  },
  {
    id: "wenxin",
    name: "文心一言",
    domain: "yiyan.baidu.com",
    url: "https://yiyan.baidu.com",
    desc: "百度生成式 AI 产品，支持知识问答、创作与智能体应用。",
    category: "assistant",
    tags: ["百度生态", "中文", "知识问答"],
    rating: 4.4,
    favs: 12180,
    pricing: "免费",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2023-03",
  },
  {
    id: "tongyi",
    name: "通义千问",
    domain: "tongyi.aliyun.com",
    url: "https://tongyi.aliyun.com",
    desc: "阿里云大模型助手，覆盖问答、编程、办公与创作场景。",
    category: "assistant",
    tags: ["阿里生态", "办公", "创作"],
    rating: 4.5,
    favs: 11350,
    pricing: "免费",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2023-04",
  },
  {
    id: "spark",
    name: "讯飞星火",
    domain: "xinghuo.xfyun.cn",
    url: "https://xinghuo.xfyun.cn",
    desc: "科大讯飞认知大模型，语音能力突出，支持多端协同。",
    category: "assistant",
    tags: ["语音", "中文", "认知"],
    rating: 4.4,
    favs: 9860,
    pricing: "免费",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2023-05",
  },
  {
    id: "zhipu",
    name: "智谱清言",
    domain: "chatglm.cn",
    url: "https://chatglm.cn",
    desc: "智谱 AI 基于 ChatGLM 打造的智能助手，擅长代码与逻辑推理。",
    category: "assistant",
    tags: ["推理", "代码", "中文"],
    rating: 4.5,
    favs: 9020,
    pricing: "免费",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2023-06",
  },
  {
    id: "grok",
    name: "Grok",
    domain: "grok.com",
    url: "https://grok.com",
    desc: "xAI 推出的对话助手，实时信息获取与幽默风格是其特色。",
    category: "assistant",
    tags: ["实时信息", "X 生态", "通用"],
    rating: 4.6,
    favs: 10320,
    pricing: "付费",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2023-11",
  },
  {
    id: "metaai",
    name: "Meta AI",
    domain: "meta.ai",
    url: "https://www.meta.ai",
    desc: "Meta 开源 Llama 模型驱动的助手，支持网页与社媒场景。",
    category: "assistant",
    tags: ["开源", "社交", "通用"],
    rating: 4.2,
    favs: 6540,
    pricing: "免费",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2023-09",
  },
  {
    id: "copilot-code",
    name: "GitHub Copilot",
    domain: "github.com",
    url: "https://github.com/features/copilot",
    desc: "GitHub 与 OpenAI 合作推出的 AI 编程助手，支持补全、对话与代理。",
    category: "code",
    tags: ["代码补全", "IDE", "代理"],
    rating: 4.8,
    favs: 21480,
    pricing: "付费",
    platforms: ["IDE 插件", "Web", "桌面"],
    featured: true,
    added: "2021-10",
  },
  {
    id: "cursor",
    name: "Cursor",
    domain: "cursor.com",
    url: "https://cursor.com",
    desc: "AI 原生的代码编辑器，基于 VS Code，支持多文件代理编辑。",
    category: "code",
    tags: ["编辑器", "代理", "重构"],
    rating: 4.9,
    favs: 23890,
    pricing: "免费额度",
    platforms: ["桌面", "Web"],
    featured: true,
    added: "2023-03",
  },
  {
    id: "windsurf",
    name: "Windsurf",
    domain: "windsurf.com",
    url: "https://windsurf.com",
    desc: "Codeium 团队的 AI IDE，强调 Flow Agent 与上下文感知。",
    category: "code",
    tags: ["编辑器", "代理", "上下文"],
    rating: 4.7,
    favs: 12680,
    pricing: "免费额度",
    platforms: ["桌面"],
    featured: false,
    added: "2024-01",
  },
  {
    id: "trae",
    name: "Trae",
    domain: "trae.ai",
    url: "https://www.trae.ai",
    desc: "字节跳动 AI IDE，内置对话编程与项目级智能体。",
    category: "code",
    tags: ["编辑器", "中文", "代理"],
    rating: 4.7,
    favs: 11240,
    pricing: "免费",
    platforms: ["桌面"],
    featured: false,
    added: "2024-06",
  },
  {
    id: "replit",
    name: "Replit",
    domain: "replit.com",
    url: "https://replit.com",
    desc: "云端开发环境，Agent 可直接从需求构建并部署完整应用。",
    category: "code",
    tags: ["云端", "部署", "Agent"],
    rating: 4.5,
    favs: 9680,
    pricing: "免费额度",
    platforms: ["Web", "桌面", "iOS", "Android"],
    featured: false,
    added: "2016-01",
  },
  {
    id: "codeium",
    name: "Codeium",
    domain: "codeium.com",
    url: "https://codeium.com",
    desc: "免费 AI 代码补全工具，支持主流 IDE 与多语言。",
    category: "code",
    tags: ["代码补全", "免费", "多 IDE"],
    rating: 4.5,
    favs: 7840,
    pricing: "免费额度",
    platforms: ["IDE 插件", "Web"],
    featured: false,
    added: "2022-04",
  },
  {
    id: "tabnine",
    name: "Tabnine",
    domain: "tabnine.com",
    url: "https://www.tabnine.com",
    desc: "企业级 AI 代码助手，可私有化部署，注重代码安全。",
    category: "code",
    tags: ["企业", "安全", "补全"],
    rating: 4.3,
    favs: 4260,
    pricing: "付费",
    platforms: ["IDE 插件"],
    featured: false,
    added: "2019-06",
  },
  {
    id: "v0",
    name: "v0",
    domain: "v0.dev",
    url: "https://v0.dev",
    desc: "Vercel 推出的 AI 前端生成工具，用自然语言生成 UI 组件。",
    category: "code",
    tags: ["前端", "UI 生成", "React"],
    rating: 4.8,
    favs: 14560,
    pricing: "免费额度",
    platforms: ["Web"],
    featured: false,
    added: "2023-10",
  },
  {
    id: "bolt",
    name: "Bolt.new",
    domain: "bolt.new",
    url: "https://bolt.new",
    desc: "浏览器内从零生成全栈应用，可预览、编辑并一键部署。",
    category: "code",
    tags: ["全栈", "浏览器", "部署"],
    rating: 4.7,
    favs: 13280,
    pricing: "免费额度",
    platforms: ["Web"],
    featured: false,
    added: "2024-04",
  },
  {
    id: "lovable",
    name: "Lovable",
    domain: "lovable.dev",
    url: "https://lovable.dev",
    desc: "用提示词快速构建可发布的 Web 应用，适合原型与 MVP。",
    category: "code",
    tags: ["MVP", "Web 应用", "提示词"],
    rating: 4.6,
    favs: 10420,
    pricing: "免费额度",
    platforms: ["Web"],
    featured: false,
    added: "2024-05",
  },
  {
    id: "devin",
    name: "Devin",
    domain: "cognition.ai",
    url: "https://cognition.ai",
    desc: "Cognition 打造的 AI 软件工程师，可独立规划并完成任务。",
    category: "code",
    tags: ["Agent", "自动化", "工程"],
    rating: 4.4,
    favs: 7120,
    pricing: "付费",
    platforms: ["Web"],
    featured: false,
    added: "2024-03",
  },
  {
    id: "midjourney",
    name: "Midjourney",
    domain: "midjourney.com",
    url: "https://www.midjourney.com",
    desc: "高质量 AI 图像生成工具，艺术风格与质感表现突出。",
    category: "image",
    tags: ["图像生成", "艺术", "Discord"],
    rating: 4.9,
    favs: 25670,
    pricing: "付费",
    platforms: ["Web", "Discord"],
    featured: true,
    added: "2022-07",
  },
  {
    id: "sd",
    name: "Stable Diffusion",
    domain: "stability.ai",
    url: "https://stability.ai",
    desc: "开源图像生成模型家族，支持本地部署与精细控制。",
    category: "image",
    tags: ["开源", "本地部署", "模型"],
    rating: 4.7,
    favs: 18430,
    pricing: "开源",
    platforms: ["Web", "桌面", "本地"],
    featured: false,
    added: "2022-08",
  },
  {
    id: "leonardo",
    name: "Leonardo AI",
    domain: "leonardo.ai",
    url: "https://leonardo.ai",
    desc: "面向游戏与设计的 AI 图像生成平台，提供大量风格模型。",
    category: "image",
    tags: ["游戏资产", "风格模型", "设计"],
    rating: 4.6,
    favs: 9870,
    pricing: "免费额度",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2022-12",
  },
  {
    id: "ideogram",
    name: "Ideogram",
    domain: "ideogram.ai",
    url: "https://ideogram.ai",
    desc: "以准确文字渲染见长的 AI 图像生成工具。",
    category: "image",
    tags: ["文字渲染", "海报", "图像生成"],
    rating: 4.6,
    favs: 8460,
    pricing: "免费额度",
    platforms: ["Web", "iOS"],
    featured: false,
    added: "2023-08",
  },
  {
    id: "canva",
    name: "Canva AI",
    domain: "canva.com",
    url: "https://www.canva.com",
    desc: "在线设计平台内置 AI 套件，支持一键成图、改文案与扩图。",
    category: "image",
    tags: ["设计平台", "模板", "一键生成"],
    rating: 4.7,
    favs: 14210,
    pricing: "免费额度",
    platforms: ["Web", "iOS", "Android", "桌面"],
    featured: false,
    added: "2023-03",
  },
  {
    id: "firefly",
    name: "Adobe Firefly",
    domain: "firefly.adobe.com",
    url: "https://firefly.adobe.com",
    desc: "Adobe 创意生成模型，深度整合 Photoshop 与 Illustrator。",
    category: "image",
    tags: ["Adobe", "创意", "生成式填充"],
    rating: 4.5,
    favs: 7830,
    pricing: "免费额度",
    platforms: ["Web", "桌面"],
    featured: false,
    added: "2023-03",
  },
  {
    id: "removebg",
    name: "Remove.bg",
    domain: "remove.bg",
    url: "https://www.remove.bg",
    desc: "一键抠图与背景替换，API 支持批量处理。",
    category: "image",
    tags: ["抠图", "背景替换", "API"],
    rating: 4.6,
    favs: 10240,
    pricing: "免费额度",
    platforms: ["Web", "桌面", "API"],
    featured: false,
    added: "2018-06",
  },
  {
    id: "meitu",
    name: "美图设计室",
    domain: "design.meitu.com",
    url: "https://design.meitu.com",
    desc: "美图旗下 AI 设计工具，主打电商素材与海报生成。",
    category: "image",
    tags: ["电商", "海报", "中文"],
    rating: 4.4,
    favs: 6740,
    pricing: "免费额度",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2023-05",
  },
  {
    id: "recraft",
    name: "Recraft",
    domain: "recraft.ai",
    url: "https://www.recraft.ai",
    desc: "生成矢量图、图标与品牌视觉的 AI 工具，风格统一可控。",
    category: "image",
    tags: ["矢量图", "品牌", "图标"],
    rating: 4.5,
    favs: 5920,
    pricing: "免费额度",
    platforms: ["Web"],
    featured: false,
    added: "2023-07",
  },
  {
    id: "suno",
    name: "Suno",
    domain: "suno.com",
    url: "https://suno.com",
    desc: "用文字生成完整歌曲，支持人声、曲风与歌词创作。",
    category: "video",
    tags: ["音乐生成", "人声", "歌词"],
    rating: 4.8,
    favs: 16430,
    pricing: "免费额度",
    platforms: ["Web", "iOS", "Android"],
    featured: true,
    added: "2023-12",
  },
  {
    id: "udio",
    name: "Udio",
    domain: "udio.com",
    url: "https://www.udio.com",
    desc: "高质量 AI 音乐生成平台，音质细腻，支持风格扩展。",
    category: "video",
    tags: ["音乐生成", "音质", "创作"],
    rating: 4.5,
    favs: 7420,
    pricing: "免费额度",
    platforms: ["Web"],
    featured: false,
    added: "2024-04",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    domain: "elevenlabs.io",
    url: "https://elevenlabs.io",
    desc: "顶级 AI 语音合成平台，支持声音克隆、配音与多语言。",
    category: "video",
    tags: ["语音合成", "声音克隆", "配音"],
    rating: 4.8,
    favs: 12840,
    pricing: "免费额度",
    platforms: ["Web", "iOS", "Android", "API"],
    featured: false,
    added: "2023-01",
  },
  {
    id: "runway",
    name: "Runway",
    domain: "runwayml.com",
    url: "https://runwayml.com",
    desc: "专业级 AI 视频生成与编辑平台，支持文生视频、抹除等。",
    category: "video",
    tags: ["文生视频", "视频编辑", "专业"],
    rating: 4.7,
    favs: 13560,
    pricing: "付费",
    platforms: ["Web", "iOS"],
    featured: false,
    added: "2018-12",
  },
  {
    id: "pika",
    name: "Pika",
    domain: "pika.art",
    url: "https://pika.art",
    desc: "轻量 AI 视频生成工具，擅长动效与创意转场。",
    category: "video",
    tags: ["视频生成", "动效", "创意"],
    rating: 4.5,
    favs: 6840,
    pricing: "免费额度",
    platforms: ["Web", "Discord"],
    featured: false,
    added: "2023-11",
  },
  {
    id: "luma",
    name: "Luma Dream Machine",
    domain: "lumalabs.ai",
    url: "https://lumalabs.ai",
    desc: "Luma 推出的视频生成模型，画质稳定，支持图生视频。",
    category: "video",
    tags: ["视频生成", "图生视频", "3D"],
    rating: 4.6,
    favs: 8210,
    pricing: "免费额度",
    platforms: ["Web"],
    featured: false,
    added: "2024-06",
  },
  {
    id: "keling",
    name: "可灵 AI",
    domain: "klingai.kuaishou.com",
    url: "https://klingai.kuaishou.com",
    desc: "快手旗下 AI 视频生成工具，支持长视频与运动控制。",
    category: "video",
    tags: ["视频生成", "中文", "长视频"],
    rating: 4.7,
    favs: 9860,
    pricing: "免费额度",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2024-06",
  },
  {
    id: "hailuo",
    name: "海螺 AI",
    domain: "hailuoai.com",
    url: "https://hailuoai.com",
    desc: "MiniMax 旗下多模态助手与视频生成产品。",
    category: "video",
    tags: ["多模态", "视频生成", "中文"],
    rating: 4.5,
    favs: 7380,
    pricing: "免费额度",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2024-04",
  },
  {
    id: "heygen",
    name: "HeyGen",
    domain: "heygen.com",
    url: "https://www.heygen.com",
    desc: "AI 数字人视频平台，支持口型同步与多语言翻译。",
    category: "video",
    tags: ["数字人", "口型同步", "翻译"],
    rating: 4.6,
    favs: 8620,
    pricing: "免费额度",
    platforms: ["Web"],
    featured: false,
    added: "2022-11",
  },
  {
    id: "notion",
    name: "Notion AI",
    domain: "notion.so",
    url: "https://www.notion.so/product/ai",
    desc: "知识库与笔记工具内置 AI，支持问答、写作与汇总。",
    category: "office",
    tags: ["知识库", "笔记", "写作"],
    rating: 4.7,
    favs: 15420,
    pricing: "付费",
    platforms: ["Web", "iOS", "Android", "桌面"],
    featured: true,
    added: "2023-02",
  },
  {
    id: "wps",
    name: "WPS AI",
    domain: "ai.wps.cn",
    url: "https://ai.wps.cn",
    desc: "金山办公 AI 助手，覆盖文档、表格、演示与 PDF。",
    category: "office",
    tags: ["办公", "文档", "中文"],
    rating: 4.5,
    favs: 11280,
    pricing: "免费额度",
    platforms: ["Web", "桌面", "iOS", "Android"],
    featured: false,
    added: "2023-07",
  },
  {
    id: "feishu",
    name: "飞书智能伙伴",
    domain: "feishu.cn",
    url: "https://www.feishu.cn/product/ai",
    desc: "飞书内置企业 AI 助手，辅助会议、文档与流程协作。",
    category: "office",
    tags: ["企业协作", "会议", "文档"],
    rating: 4.5,
    favs: 8930,
    pricing: "免费额度",
    platforms: ["Web", "桌面", "iOS", "Android"],
    featured: false,
    added: "2023-08",
  },
  {
    id: "grammarly",
    name: "Grammarly",
    domain: "grammarly.com",
    url: "https://www.grammarly.com",
    desc: "英文写作校对与润色助手，支持浏览器插件与文档集成。",
    category: "office",
    tags: ["英文写作", "校对", "插件"],
    rating: 4.6,
    favs: 11840,
    pricing: "免费额度",
    platforms: ["Web", "插件", "桌面", "iOS", "Android"],
    featured: false,
    added: "2009-07",
  },
  {
    id: "gamma",
    name: "Gamma",
    domain: "gamma.app",
    url: "https://gamma.app",
    desc: "用提示词快速生成演示文稿、文档与网页。",
    category: "office",
    tags: ["演示文稿", "生成", "设计"],
    rating: 4.7,
    favs: 12980,
    pricing: "免费额度",
    platforms: ["Web"],
    featured: false,
    added: "2023-06",
  },
  {
    id: "beautiful",
    name: "Beautiful.ai",
    domain: "beautiful.ai",
    url: "https://www.beautiful.ai",
    desc: "智能排版的演示工具，自动保持设计规范与一致性。",
    category: "office",
    tags: ["演示", "智能排版", "设计"],
    rating: 4.4,
    favs: 5860,
    pricing: "付费",
    platforms: ["Web"],
    featured: false,
    added: "2018-02",
  },
  {
    id: "otter",
    name: "Otter.ai",
    domain: "otter.ai",
    url: "https://otter.ai",
    desc: "实时会议转录与纪要生成，支持多人识别。",
    category: "office",
    tags: ["会议转录", "纪要", "语音"],
    rating: 4.5,
    favs: 7420,
    pricing: "免费额度",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2016-08",
  },
  {
    id: "fireflies",
    name: "Fireflies.ai",
    domain: "fireflies.ai",
    url: "https://fireflies.ai",
    desc: "自动记录会议并生成摘要，集成 Zoom、Teams 等工具。",
    category: "office",
    tags: ["会议", "摘要", "集成"],
    rating: 4.5,
    favs: 6530,
    pricing: "免费额度",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2020-03",
  },
  {
    id: "zapier",
    name: "Zapier AI",
    domain: "zapier.com",
    url: "https://zapier.com",
    desc: "连接数千款应用的自动化平台，AI 可帮助创建流程。",
    category: "office",
    tags: ["自动化", "集成", "工作流"],
    rating: 4.6,
    favs: 9860,
    pricing: "付费",
    platforms: ["Web"],
    featured: false,
    added: "2012-01",
  },
  {
    id: "perplexity",
    name: "Perplexity",
    domain: "perplexity.ai",
    url: "https://www.perplexity.ai",
    desc: "AI 搜索引擎，回答附带来源引用，支持深度研究。",
    category: "search",
    tags: ["搜索", "引用", "研究"],
    rating: 4.8,
    favs: 19340,
    pricing: "免费额度",
    platforms: ["Web", "iOS", "Android"],
    featured: true,
    added: "2022-12",
  },
  {
    id: "metaso",
    name: "秘塔 AI 搜索",
    domain: "metaso.cn",
    url: "https://metaso.cn",
    desc: "中文 AI 搜索引擎，无广告、带来源，支持学术与文库。",
    category: "search",
    tags: ["中文", "学术", "无广告"],
    rating: 4.7,
    favs: 12460,
    pricing: "免费",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2024-01",
  },
  {
    id: "quark",
    name: "夸克 AI",
    domain: "quark.cn",
    url: "https://www.quark.cn",
    desc: "夸克浏览器内置 AI 搜索与工具，覆盖学习、办公场景。",
    category: "search",
    tags: ["浏览器", "学习", "工具"],
    rating: 4.4,
    favs: 6920,
    pricing: "免费",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2023-10",
  },
  {
    id: "notebooklm",
    name: "NotebookLM",
    domain: "notebooklm.google.com",
    url: "https://notebooklm.google.com",
    desc: "Google 文档研究助手，基于上传资料生成摘要与播客。",
    category: "search",
    tags: ["文档研究", "摘要", "播客"],
    rating: 4.8,
    favs: 13870,
    pricing: "免费",
    platforms: ["Web"],
    featured: true,
    added: "2023-07",
  },
  {
    id: "consensus",
    name: "Consensus",
    domain: "consensus.app",
    url: "https://consensus.app",
    desc: "面向科研论文的 AI 搜索，直接给出证据与结论。",
    category: "search",
    tags: ["论文", "科研", "证据"],
    rating: 4.6,
    favs: 6840,
    pricing: "免费额度",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2023-02",
  },
  {
    id: "elicit",
    name: "Elicit",
    domain: "elicit.com",
    url: "https://elicit.com",
    desc: "AI 文献综述工具，自动提取论文关键信息。",
    category: "search",
    tags: ["文献综述", "论文", "研究"],
    rating: 4.5,
    favs: 5230,
    pricing: "免费额度",
    platforms: ["Web"],
    featured: false,
    added: "2022-09",
  },
  {
    id: "wolfram",
    name: "Wolfram Alpha",
    domain: "wolframalpha.com",
    url: "https://www.wolframalpha.com",
    desc: "计算知识引擎，擅长数学、科学与数据查询。",
    category: "search",
    tags: ["计算", "数学", "知识"],
    rating: 4.5,
    favs: 7430,
    pricing: "付费",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2009-05",
  },
  {
    id: "character",
    name: "Character.AI",
    domain: "character.ai",
    url: "https://character.ai",
    desc: "与 AI 角色对话互动，支持自定义人格与群聊。",
    category: "life",
    tags: ["角色扮演", "对话", "娱乐"],
    rating: 4.6,
    favs: 11870,
    pricing: "免费",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2022-09",
  },
  {
    id: "replika",
    name: "Replika",
    domain: "replika.com",
    url: "https://replika.com",
    desc: "AI 陪伴应用，提供情感陪伴与日常对话。",
    category: "life",
    tags: ["陪伴", "情感", "对话"],
    rating: 4.1,
    favs: 5480,
    pricing: "免费额度",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2017-03",
  },
  {
    id: "pi",
    name: "Pi",
    domain: "pi.ai",
    url: "https://pi.ai",
    desc: "Inflection 推出的友好型 AI 对话伙伴。",
    category: "life",
    tags: ["对话", "友好", "日常"],
    rating: 4.3,
    favs: 3860,
    pricing: "免费",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2023-05",
  },
  {
    id: "julius",
    name: "Julius AI",
    domain: "julius.ai",
    url: "https://julius.ai",
    desc: "自然语言数据分析助手，可上传数据并生成图表。",
    category: "data",
    tags: ["数据分析", "图表", "Python"],
    rating: 4.5,
    favs: 5480,
    pricing: "免费额度",
    platforms: ["Web"],
    featured: false,
    added: "2023-04",
  },
  {
    id: "datacamp",
    name: "DataCamp AI",
    domain: "datacamp.com",
    url: "https://www.datacamp.com",
    desc: "数据科学学习平台，AI 助手辅助代码与练习。",
    category: "data",
    tags: ["学习", "数据科学", "Python"],
    rating: 4.4,
    favs: 4320,
    pricing: "付费",
    platforms: ["Web", "iOS", "Android"],
    featured: false,
    added: "2014-01",
  },
  {
    id: "powerbi",
    name: "Power BI Copilot",
    domain: "powerbi.microsoft.com",
    url: "https://powerbi.microsoft.com",
    desc: "微软商业智能内置 Copilot，用自然语言生成报表。",
    category: "data",
    tags: ["商业智能", "报表", "微软"],
    rating: 4.5,
    favs: 5210,
    pricing: "付费",
    platforms: ["Web", "桌面"],
    featured: false,
    added: "2024-01",
  },
  {
    id: "tableau",
    name: "Tableau AI",
    domain: "tableau.com",
    url: "https://www.tableau.com",
    desc: "可视化分析平台内置 AI，自动发现数据洞察。",
    category: "data",
    tags: ["可视化", "洞察", "分析"],
    rating: 4.3,
    favs: 3960,
    pricing: "付费",
    platforms: ["Web", "桌面"],
    featured: false,
    added: "2024-02",
  },
  {
    id: "airtable",
    name: "Airtable AI",
    domain: "airtable.com",
    url: "https://www.airtable.com",
    desc: "低代码数据库平台，AI 可自动总结、生成字段与流程。",
    category: "data",
    tags: ["低代码", "数据库", "自动化"],
    rating: 4.4,
    favs: 6180,
    pricing: "免费额度",
    platforms: ["Web", "iOS", "Android", "桌面"],
    featured: false,
    added: "2013-04",
  },
];
